apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-podinfo
  namespace: argocd
spec:
  destination:
    namespace: team2
    name: in-cluster
  project: team2
  source:
    path: './teams/team2/applications/podinfo'
    repoURL: https://github.com/TaneBarriball-IAG/argo-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true