apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.teamname }}-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Team application resources
  sourceRepos:
  - 'argo-demo'
  destinations:
  - namespace: "{{ .Values.teamname }}"
    server: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  sourceRepos:
  - '*'
