apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
- name: podinfo
  repo: https://stefanprodan.github.io/podinfo
  version: x.x.x
  releaseName: team1-podinfo

patchesStrategicMerge:
- overlays/service-podinfo.yaml
