apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-podinfo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: argo-system
  source:
    path: './teams/team1/applications/podinfo'
    repoURL: https://github.com/TaneBarriball-IAG/argo-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true