apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PostSync
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: argo-system
  source:
    path: './teams'
    repoURL: https://github.com/TaneBarriball-IAG/argo-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true