apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-setup
  namespace: argocd
spec:
  destination:
    namespace: team1
    name: in-cluster
  project: argo-projects
  source:
    repoURL: https://github.com/TaneBarriball-IAG/argo-demo.git
    path: teams/team1
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true