apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team3-podinfo
  namespace: argocd
spec:
  destination:
    namespace: team3
    name: in-cluster
  project: team3
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: x.x.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true