apiVersion: v1
kind: Secret
metadata:
  name: argo-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/TaneBarriball-IAG/argo-demo.git
  password: TOKEN
  username: random-username